# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TODO deployment

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Unit Tests
      run: npm test

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build -t todo-app .

    - name: Tag Docker Image
      run: docker tag todo-app danieltello3/todo-app:latest

    - name: Push to Dockerhub
      run: docker push danieltello3/todo-app:latest

  deploy:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull danieltello3/todo-app:latest

    - name: Delete Old Docker Container
      run: docker rm -f todo-app-container || true
      
    - name: Run Docker Container
      run: docker run -d -p 3000:3000 --name todo-app-container danieltello3/todo-app:latest
